AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
